name: promptly
description: A collection of customizable interactive command-line components.
version: 1.0.0-alpha.4
homepage: https://zoocityboy.github.io/promptly
documentation: https://pub.dev/documentation/promptly/latest/
repository: https://github.com/zoocityboy/promptly
issue_tracker: https://github.com/zoocityboy/promptly/issues
topics:
  - command-line
  - interactive
  - components
  - dart
  - cli
platforms:
  linux:
  macos:
  windows:
screenshots:
  - description: A prompt with a single option.
    path: assets/promptly.png
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  cli_table: ^1.0.2
  dart_console: ^4.1.1
  intl: ^0.19.0
  io: ^1.0.5
  meta: ^1.15.0
  path: ^1.9.1
  tint: ^2.0.0
  version: ^3.0.2
  wcwidth: ^0.0.4

dev_dependencies:
  equatable: ^2.0.7
  lints: ^5.1.1
  test: ^1.25.14
  test_coverage_badge: ^0.3.2

